[package]
name = "gpx_kml_convert_wasm"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
console_error_panic_hook = { version = "0.1.6", optional = true }
gpx_kml_convert = { path = "../gpx_kml_convert" }
