[package]
name = "gpx_kml_convert"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
gpx = "0.8"
kml = { version = "0.4.2", default-features = false }
chrono = "0.4"
thiserror = "1.0"
